# Docker Compose override for development
# This file is automatically loaded by docker-compose and overrides settings in docker-compose.yml
# Use this for local development and testing

version: '3.8'

services:
  # MySQL Database - Development overrides
  mysql:
    ports:
      - "3308:3306"  # Different port for local development
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-19980223}
      MYSQL_DATABASE: ${DB_NAME:-cdb_mosh_p1_ecommerce_app_dev}
      # No MYSQL_USER needed when using root
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

  # Spring Boot Application - Development overrides
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder  # Use builder stage for development
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-local}
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-cdb_mosh_p1_ecommerce_app_dev}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-19980223}
      SWAGGER_ENABLED: true  # Enable Swagger in development
    ports:
      - "8080:8080"
    volumes:
      # Mount source code for hot reload (if using spring-boot-devtools)
      - ./src:/app/src:ro
      - ./target:/app/target
      - dev_logs:/app/logs
    command: ["sh", "-c", "java -Dspring.profiles.active=local -jar app.jar"]

  # Development tools
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - mosh-store-network
    profiles:
      - development

volumes:
  mysql_dev_data:
    driver: local
  dev_logs:
    driver: local 