server:
  port: 8080

spring:
  application:
    name: mosh-store
  config:
      import: "optional:classpath:.env"
  datasource:
    url: jdbc:mysql://localhost:3308/store

# Payment Configuration
payment:
  default-method: paypal  # Default payment method: paypal, stripe, creditCard
  gateway: ${payment.default-method}  # For backward compatibility

# Stripe Configuration
stripe:
  enabled: true
  apiUrl: https://api.stripe.com
  timeout: 1000
  supportedCurrencies:
    - USD
    - EUR
    - GBP

# PayPal Configuration (example)
paypal:
  enabled: true
  apiUrl: https://api.paypal.com
  timeout: 2000

# Credit Card Configuration (example)  
creditCard:
  enabled: true
  timeout: 1500

  