server:
  port: 8080

spring:
  application:
    name: mosh-store
    version: 1.0.0
  config:
      import: "optional:file:./src/main/resources/.env"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:19980223}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      connection-test-query: SELECT 1
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none  # DISABLED - Flyway controls schema
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  # Flyway Configuration (Spring Boot Integration)
  flyway:
    enabled: true  # Auto-run on startup (can be disabled for manual control)
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
    sql-migration-prefix: V
    sql-migration-suffixes: .sql
    # Optional: Disable auto-migration in production
    # enabled: false  # Uncomment for manual migration control
    
# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true

# Payment Configuration - Use kebab-case consistently
payment:
  default-method: paypal  # Default payment method: paypal, stripe, credit-card

# Stripe Configuration
stripe:
  enabled: true
  api-url: https://api.stripe.com
  timeout: 1000
  public-key: pk_test_demo_public_key
  secret-key: sk_test_demo_secret_key
  webhook-secret: whsec_demo_webhook_secret
  supported-currencies:
    - USD
    - EUR
    - GBP
    - CAD

# PayPal Configuration - Use kebab-case
paypal:
  enabled: true
  api-url: https://api.paypal.com
  environment: sandbox
  timeout: 2000
  client-id: demo_paypal_client_id
  client-secret: demo_paypal_client_secret
  supported-currencies:
    - USD
    - EUR
    - GBP
    - CAD
    - AUD
  fee-percentage: 2.9
  fixed-fee: 0.30

# Credit Card Configuration - Use kebab-case
credit-card:
  enabled: true
  processor-name: "Secure Payment Processor"
  timeout: 1500
  cvv-required: true
  billing-address-required: false
  max-retry-attempts: 3
  accepted-card-types:
    - VISA
    - MASTERCARD
    - AMERICAN_EXPRESS
    - DISCOVER
  processing-fee-percentage: 2.5
  require-cvv: true
  require-billing-address: false
  processingFeePercentage: 2.5
  requireCvv: true
  requireBillingAddress: false